# Generated by Django 5.0.4 on 2024-05-05 11:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('filmlar', 'filmlar'), ('seriallar', 'seriallar'), ('animelar', 'animelar'), ('primyeralar', 'primyeralar')], default='primyeralar', max_length=25)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PartModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part', to='models.moviemodels')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonModels',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='models.partmodels')),
            ],
        ),
    ]
